using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RockPaperScissors
{
    public abstract class Player
    {
        public string Name { get; set; }

        public Player(string Name)
        {
            this.Name = Name;
        }

        // When a new player is instanciated, a new RPS value is generated by calling this method. 
        public abstract string GenerateRoshambo();
    }
}
